const images = [
  "/space-1.png",
  "/space-2.png",
  "/space-3.png",
  "/space-4.png",
  "/space-5.png",
  "/space-6.png",
  "/space-7.png",
  "/space-8.png",
  "/hero.png",
  "/about-image-3.png",
];

const desc = "lorem ipsum";

export const spaces = [
  {
    id: 1,
    title: "Riverside Focus Studio",
    description: desc,
    size: 120,
    images: [images[0], images[2], images[4], images[6], images[8]],
    slug: "riverside-focus-studio",
    city: "London",
    country: "United Kingdom",
  },
  {
    id: 2,
    title: "Canary Wharf Executive Suite",
    description: desc,
    size: 140,
    images: [images[1], images[3], images[5], images[7], images[9]],
    slug: "canary-wharf-executive-suite",
    city: "London",
    country: "United Kingdom",
  },
  {
    id: 3,
    title: "Soho Creative Loft",
    description: desc,
    size: 160,
    images: [images[0], images[3], images[4], images[7], images[8]],
    slug: "soho-creative-loft",
    city: "London",
    country: "United Kingdom",
  },
  {
    id: 4,
    title: "Shoreditch Startup Hub",
    description: desc,
    size: 180,
    images: [images[2], images[3], images[6], images[7], images[9]],
    slug: "shoreditch-startup-hub",
    city: "London",
    country: "United Kingdom",
  },
  {
    id: 5,
    title: "Hyde Park Executive Workspace",
    description: desc,
    size: 150,
    images: [images[1], images[2], images[5], images[6], images[8]],
    slug: "hyde-park-executive-workspace",
    city: "London",
    country: "United Kingdom",
  },
  {
    id: 6,
    title: "Montmartre Creative Atelier",
    description: desc,
    size: 130,
    images: [images[0], images[4], images[5], images[7], images[9]],
    slug: "montmartre-creative-atelier",
    city: "Paris",
    country: "France",
  },
  {
    id: 7,
    title: "Left Bank Study Loft",
    description: desc,
    size: 170,
    images: [images[1], images[3], images[6], images[8], images[9]],
    slug: "left-bank-study-loft",
    city: "Paris",
    country: "France",
  },
  {
    id: 8,
    title: "Marais Collaborative Space",
    description: desc,
    size: 200,
    images: [images[0], images[2], images[4], images[6], images[7]],
    slug: "marais-collaborative-space",
    city: "Paris",
    country: "France",
  },
  {
    id: 9,
    title: "Champs Elysees Executive Studio",
    description: desc,
    size: 160,
    images: [images[1], images[2], images[5], images[7], images[8]],
    slug: "champs-elysees-executive-studio",
    city: "Paris",
    country: "France",
  },
  {
    id: 10,
    title: "Saint Germain Focus Room",
    description: desc,
    size: 140,
    images: [images[0], images[3], images[4], images[6], images[9]],
    slug: "saint-germain-focus-room",
    city: "Paris",
    country: "France",
  },
  {
    id: 11,
    title: "Manhattan Executive Office",
    description: desc,
    size: 220,
    images: [images[1], images[4], images[5], images[7], images[8]],
    slug: "manhattan-executive-office",
    city: "New York",
    country: "United States",
  },
  {
    id: 12,
    title: "Brooklyn Creative Workspace",
    description: desc,
    size: 180,
    images: [images[0], images[2], images[3], images[6], images[9]],
    slug: "brooklyn-creative-workspace",
    city: "New York",
    country: "United States",
  },
  {
    id: 13,
    title: "SoHo Premium Studio",
    description: desc,
    size: 150,
    images: [images[1], images[3], images[4], images[6], images[8]],
    slug: "soho-premium-studio",
    city: "New York",
    country: "United States",
  },
  {
    id: 14,
    title: "Wall Street Executive Hub",
    description: desc,
    size: 210,
    images: [images[2], images[4], images[5], images[7], images[9]],
    slug: "wall-street-executive-hub",
    city: "New York",
    country: "United States",
  },
  {
    id: 15,
    title: "Central Park Focus Suite",
    description: desc,
    size: 160,
    images: [images[0], images[1], images[5], images[6], images[8]],
    slug: "central-park-focus-suite",
    city: "New York",
    country: "United States",
  },
  {
    id: 16,
    title: "Chelsea Designer Loft",
    description: desc,
    size: 190,
    images: [images[1], images[3], images[5], images[7], images[8]],
    slug: "chelsea-designer-loft",
    city: "New York",
    country: "United States",
  },
  {
    id: 17,
    title: "Greenwich Village Studio",
    description: desc,
    size: 140,
    images: [images[0], images[2], images[6], images[7], images[9]],
    slug: "greenwich-village-studio",
    city: "New York",
    country: "United States",
  },
  {
    id: 18,
    title: "Canal Street Innovation Space",
    description: desc,
    size: 170,
    images: [images[1], images[2], images[4], images[6], images[8]],
    slug: "canal-street-innovation-space",
    city: "New York",
    country: "United States",
  },
  {
    id: 19,
    title: "Bastille Creative Workspace",
    description: desc,
    size: 155,
    images: [images[0], images[3], images[4], images[7], images[9]],
    slug: "bastille-creative-workspace",
    city: "Paris",
    country: "France",
  },
  {
    id: 20,
    title: "King's Cross Innovation Loft",
    description: desc,
    size: 175,
    images: [images[2], images[3], images[5], images[6], images[8]],
    slug: "kings-cross-innovation-loft",
    city: "London",
    country: "United Kingdom",
  },
];
